### ISSUE TITLE
Index: Change docker image to elasticsearch 5.x

### ISSUE THREAD

**Issue by erinreeves** [cires-ncei/metadata-catalog#47]
Updated docker image to latest elasticsearch 5.x
elasticsearch docker docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by mcquinne** [comment]
This was initially accomplished by 2568ad018e937f52335242a7e4090c5f5e4e8804. Didn't realize there was a separate issue for this part.
