### ISSUE TITLE
Storage: remove table name prefix from fields in tables. 

### ISSUE THREAD

**Issue by ChrisEsterlein** [cires-ncei/metadata-catalog#49]
e.g. collection_name -> name and collection_metadata -> metadata

collection_name -> name
schema_name -> name
collection_schema -> metadata_schema
collection_metadata -> metadata

granule_metadata -> metadata
granule_schema -> metadata_schema
granule_size -> size_bytes

**Comment by zebdelk** [comment]
Make sure to update any existing API tests using these fields (test should be using minimal fields, so I'm not sure they're using them at all right now)

**Comment by zebdelk** [comment]
Update CQL scripts.

**Comment by erinreeves** [comment]
Found collection_name, schema_name, collection_schema
